export const reservations = [
  {
    id: 1,
    customer: "Adrienne Miller",
    subtitle: "VIP Guest • 12 previous visits",
    guests: 4,
    table: "12",
    status: "Confirmed",
    source: "Web",
    time: "19:30",
    avatar: "AM",
    statusColor: "green",
    avatarColor: "bg-[#F6DDD3]",
  },
  {
    id: 2,
    customer: "Robert Jenkins",
    subtitle: "Special Request:\nAnniversary",
    guests: 2,
    table: "04",
    status: "Seated",
    source: "AI Call",
    time: "20:15",
    avatar: "RJ",
    statusColor: "orange",
    highlight: true,
    avatarColor: "bg-[#ECECEC]",
  },
  {
    id: 3,
    customer: "Sarah Kim",
    subtitle: "New Customer",
    guests: 6,
    table: "22",
    status: "Pending",
    source: "AI Call",
    time: "18:00",
    avatar: "SK",
    statusColor: "gray",
    avatarColor: "bg-[#ECECEC]",
    approve: true,
  },
  {
  id: 4,
  customer: "Lucas Dupont",
  subtitle: "No Show 2x",
  guests: 2,
  table: "--",
  status: "Cancelled",
  source: "Web",
  time: "21:00",
  avatar: "LD",
  statusColor: "red",
  avatarColor: "bg-[#FFE8EC]",
},
  {
    id: 5,
    customer: "Helena White",
    subtitle: "Corporate Account",
    guests: 10,
    table: "T-1 + T-2",
    status: "Confirmed",
    source: "Web",
    time: "20:00",
    avatar: "HW",
    statusColor: "green",
    avatarColor: "bg-[#F6DDD3]",
  },
];